--- #YAML:1.0
name:               VANAMBURG-MAGIC-BCS
version:            1.0.1
abstract:           Models Richard Osterlind's Breakthrough Card System for simulations.
author:
    - Gordon Van Amburg <vanamburg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::MoreUtils:  0
    Moose:            0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
